"""Initial migration

Revision ID: dca5623aba64
Revises: 
Create Date: 2024-10-13 12:38:31.150124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca5623aba64'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professional')
    op.drop_table('available_services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_services',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professional',
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('order', sa.BLOB(), nullable=True),
    sa.Column('services', sa.BLOB(), nullable=True),
    sa.Column('YoE', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('pin', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order'], ['user.order'], ),
    sa.ForeignKeyConstraint(['services'], ['user.order'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('profile_id', 'YoE')
    )
    # ### end Alembic commands ###
