"""9 migration

Revision ID: f562e9ad2d56
Revises: e4a6ae9ed3b4
Create Date: 2024-10-17 10:43:10.476414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f562e9ad2d56'
down_revision = 'e4a6ae9ed3b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_by', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('closed_by')

    # ### end Alembic commands ###
